# Generated by Django 5.2.17 on 2026-09-13 18:55

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("field", models.CharField(max_length=120)),
                ("problem", models.TextField()),
                ("buyer", models.TextField(blank=True)),
                ("reach", models.TextField(blank=True)),
                ("workaround", models.TextField(blank=True)),
                ("advantage", models.TextField(blank=True)),
                ("delivery", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("inbox", "Investigating"),
                            ("parked", "Parked"),
                            ("archived", "Archived"),
                        ],
                        default="inbox",
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "variable_cost",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "hours_per_sale",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "hourly_value",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RateBucket",
            fields=[
                ("key", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("window", models.DateTimeField()),
                ("count", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("rules-v1", "Rules v1"), ("ai-draft", "AI draft")], max_length=20
                    ),
                ),
                ("report", models.JSONField()),
                ("input_snapshot", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="core.opportunity",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "monthly_income_target",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "experiment_budget",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "weekly_hours",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                ("target_date", models.DateField(blank=True, null=True)),
                ("focus_fields", models.TextField(blank=True)),
                ("constraints", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceMonitor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "adapter",
                    models.CharField(
                        choices=[("hackernews", "Hacker News"), ("rss", "RSS")], max_length=20
                    ),
                ),
                ("query", models.CharField(blank=True, max_length=200)),
                ("feed_url", models.URLField(blank=True, max_length=500)),
                ("interval_hours", models.PositiveIntegerField(default=24)),
                ("enabled", models.BooleanField(default=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitors",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ResearchJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("collection", "Collection"), ("review", "Review")], max_length=20
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("available_at", models.DateTimeField()),
                ("lease_until", models.DateTimeField(blank=True, null=True)),
                ("claim_token", models.UUIDField(blank=True, null=True)),
                ("result", models.JSONField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "opportunity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="core.opportunity",
                    ),
                ),
                (
                    "monitor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="core.sourcemonitor",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="opportunity",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opportunities",
                to="core.workspace",
            ),
        ),
        migrations.CreateModel(
            name="Experiment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("hypothesis", models.TextField()),
                ("action", models.TextField()),
                ("success_criteria", models.TextField()),
                ("stop_criteria", models.TextField()),
                ("budget", models.DecimalField(decimal_places=2, max_digits=12)),
                ("deadline", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("stopped", "Stopped"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("snapshot", models.JSONField(default=dict)),
                ("outcome", models.TextField(blank=True)),
                (
                    "actual_spend",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "revenue",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("paying_customers", models.PositiveIntegerField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="experiments",
                        to="core.opportunity",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiments",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("url", models.URLField(blank=True, max_length=500)),
                ("source", models.CharField(blank=True, max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("observed", "Observed"),
                            ("inferred", "Inferred"),
                            ("hypothesis", "Hypothesis"),
                            ("unknown", "Unknown"),
                            ("counterfactual", "Counterfactual"),
                        ],
                        default="observed",
                        max_length=20,
                    ),
                ),
                (
                    "stance",
                    models.CharField(
                        choices=[
                            ("supports", "Supports"),
                            ("challenges", "Challenges"),
                            ("context", "Context"),
                        ],
                        default="context",
                        max_length=20,
                    ),
                ),
                ("fingerprint", models.CharField(max_length=64)),
                ("observed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "opportunity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evidence",
                        to="core.opportunity",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-observed_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("action", models.CharField(max_length=80)),
                ("entity_id", models.UUIDField(blank=True, null=True)),
                ("detail", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="sourcemonitor",
            index=models.Index(
                fields=["enabled", "next_run_at"], name="core_source_enabled_6849ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sourcemonitor",
            index=models.Index(fields=["workspace"], name="core_source_workspa_49b405_idx"),
        ),
        migrations.AddIndex(
            model_name="researchjob",
            index=models.Index(
                fields=["status", "available_at"], name="core_resear_status_2b5e85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="researchjob",
            index=models.Index(
                fields=["workspace", "-created_at"], name="core_resear_workspa_8c0d9f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="researchjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "collection"), ("status__in", ["queued", "running"])),
                fields=("monitor",),
                name="one_pending_monitor_job",
            ),
        ),
        migrations.AddConstraint(
            model_name="researchjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "review"), ("status__in", ["queued", "running"])),
                fields=("opportunity",),
                name="one_pending_review_job",
            ),
        ),
        migrations.AddIndex(
            model_name="opportunity",
            index=models.Index(
                fields=["workspace", "-created_at"], name="core_opport_workspa_7bdfac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="opportunity",
            index=models.Index(
                fields=["workspace", "status"], name="core_opport_workspa_dc964a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="experiment",
            index=models.Index(
                fields=["workspace", "status"], name="core_experi_workspa_aababc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="experiment",
            index=models.Index(
                fields=["workspace", "-created_at"], name="core_experi_workspa_1bfd54_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="experiment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("workspace",),
                name="one_active_experiment",
            ),
        ),
        migrations.AddIndex(
            model_name="evidence",
            index=models.Index(
                fields=["workspace", "-observed_at"], name="core_eviden_workspa_f7d01e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evidence",
            index=models.Index(
                fields=["workspace", "opportunity"], name="core_eviden_workspa_fd933c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="evidence",
            constraint=models.UniqueConstraint(
                fields=("workspace", "fingerprint"), name="unique_workspace_evidence"
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["workspace", "-created_at"], name="core_audite_workspa_55ae96_idx"
            ),
        ),
    ]
